// <auto-generated />
using System;
using System.IO;
using Google.Protobuf;
using J2.Protocol;

namespace J2.Networking
{
    public static class GamePacketHandler
    {
        private delegate void PacketHandlerFunc(PacketSession session, ArraySegment<byte> buffer);
        private static readonly PacketHandlerFunc[] Handlers = new PacketHandlerFunc[ushort.MaxValue + 1];

        // CLR runs this once, before the first call, including concurrent callers.
        static GamePacketHandler()
        {
            for (int id = 0; id < Handlers.Length; id++)
                Handlers[id] = HandleInvalid;
            Register(101, S_EnterGame.Parser, BasicPacketHandler.Handle_S_EnterGame);
            Register(103, S_LeaveGame.Parser, BasicPacketHandler.Handle_S_LeaveGame);
            Register(105, S_FindMatch.Parser, BasicPacketHandler.Handle_S_FindMatch);
            Register(107, S_AcceptMatch.Parser, BasicPacketHandler.Handle_S_AcceptMatch);
            Register(109, S_Pong.Parser, BasicPacketHandler.Handle_S_Pong);
            Register(201, S_Chat.Parser, ChatPacketHandler.Handle_S_Chat);
            Register(301, S_Spawn.Parser, InGamePacketHandler.Handle_S_Spawn);
            Register(303, S_Move.Parser, InGamePacketHandler.Handle_S_Move);
            Register(305, S_RequestResult.Parser, InGamePacketHandler.Handle_S_RequestResult);
        }

        public static void HandlePacket(PacketSession session, ArraySegment<byte> buffer)
        {
            ushort id = (ushort)PacketCodec.GetId(buffer);
            Handlers[id](session, buffer);
        }

        private static void Register<T>(ushort id, MessageParser<T> parser, Action<PacketSession, T> handler)
            where T : IMessage<T>
        {
            Handlers[id] = (session, buffer) => DispatchPacket(parser, handler, session, buffer);
        }

        private static void DispatchPacket<T>(MessageParser<T> parser, Action<PacketSession, T> handler,
            PacketSession session, ArraySegment<byte> buffer) where T : IMessage<T>
        {
            T packet = PacketCodec.Parse(parser, buffer);
            handler(session, packet);
        }

        private static void HandleInvalid(PacketSession session, ArraySegment<byte> buffer)
            => throw new InvalidDataException("Unknown or wrong-direction packet ID.");

    }
}
