using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

var project = Path.GetFullPath(args[0]);
var changed = 0;
var count = 0;
var symbolSets = new[] { new[] { "UNITY_EDITOR", "DEVELOPMENT_BUILD" }, new[] { "ARENA_HEADLESS" }, Array.Empty<string>() };

foreach (var file in Directory.GetFiles(Path.Combine(project, "Assets"), "*.cs", SearchOption.AllDirectories))
{
    if (args.Length > 1 && !args.Skip(1).Any(name => string.Equals(Path.GetFileName(file), name, StringComparison.OrdinalIgnoreCase)))
    {
        continue;
    }

    var input = File.ReadAllText(file);

    if (file.EndsWith(".g.cs") || input.Contains("<auto-generated>"))
    {
        continue;
    }

    var output = input;

    foreach (var import in new[] { "System.Collections.Generic", "System.Collections", "System" })
    {
        if (!System.Text.RegularExpressions.Regex.IsMatch(output, @"(?m)^using " + System.Text.RegularExpressions.Regex.Escape(import) + @";\r?$"))
        {
            output = "using " + import + ";\r\n" + output;
        }
    }

    if (CSharpSyntaxTree.ParseText(output, new CSharpParseOptions(preprocessorSymbols: symbolSets[0])).GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error))
    {
        File.WriteAllText(file, output, new UTF8Encoding(false));
        Console.WriteLine("Skipped layout of unfinished source (imports only): " + file);
        continue;
    }

    foreach (var symbols in symbolSets)
    {
        var options = new CSharpParseOptions(preprocessorSymbols: symbols);
        var before = CSharpSyntaxTree.ParseText(output, options).GetRoot();

        if (before.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error))
        {
            throw new Exception("Parse failed: " + file);
        }

        var rewritten = new Braces().Visit(before).NormalizeWhitespace("    ", "\r\n").ToFullString();
        var after = CSharpSyntaxTree.ParseText(rewritten, options).GetRoot();
        var source = after.SyntaxTree.GetText();
        var blankBefore = new HashSet<int>();

        void Separate(SyntaxNode node)
        {
            var line = source.Lines.GetLineFromPosition(node.FullSpan.Start).LineNumber;
            var actual = source.Lines.GetLineFromPosition(node.SpanStart).LineNumber;
            // Include attached comments but not whitespace on the preceding statement's line.
            if (line < actual && source.Lines[line].ToString().Trim().Length > 0)
            {
                line++;
            }

            blankBefore.Add(line);
        }

        foreach (var type in after.DescendantNodes().OfType<TypeDeclarationSyntax>())
        {
            for (var i = 1; i < type.Members.Count; i++)
            {
                if (type.Members[i] is BaseMethodDeclarationSyntax || type.Members[i - 1] is BaseMethodDeclarationSyntax)
                {
                    Separate(type.Members[i]);
                }
            }
        }

        foreach (var block in after.DescendantNodes().OfType<BlockSyntax>())
        {
            for (var i = 1; i < block.Statements.Count; i++)
            {
                var previous = block.Statements[i - 1];
                var current = block.Statements[i];

                if (previous.Kind() != current.Kind() || previous is LocalDeclarationStatementSyntax || current is LocalFunctionStatementSyntax)
                {
                    Separate(current);
                }
            }
        }

        var result = new StringBuilder();

        for (var i = 0; i < source.Lines.Count; i++)
        {
            if (blankBefore.Contains(i) && i > 0 && source.Lines[i].ToString().Trim().Length > 0 && source.Lines[i - 1].ToString().Trim().Length > 0)
            {
                result.Append("\r\n");
            }

            result.Append(source.Lines[i].ToString()).Append("\r\n");
        }

        output = result.ToString();
        var final = CSharpSyntaxTree.ParseText(output, options).GetRoot();
        string[] Tokens(SyntaxNode node) => node.DescendantTokens().Where(t => !t.IsKind(SyntaxKind.OpenBraceToken) && !t.IsKind(SyntaxKind.CloseBraceToken)).Select(t => t.Text).ToArray();

        if (final.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error) || !Tokens(before).SequenceEqual(Tokens(final)))
        {
            throw new Exception("Token preservation check failed: " + file);
        }
    }

    output = MemberLayout.Format(output);

    count++;

    if (input != output)
    {
        File.WriteAllText(file, output, new UTF8Encoding(false));
        changed++;
    }
}

Console.WriteLine($"Checked {count} authored files; formatted {changed}. Non-brace tokens preserved in editor, headless and player configurations.");

sealed class Braces : CSharpSyntaxRewriter
{
    static StatementSyntax Wrap(StatementSyntax statement)
    {
        if (statement is BlockSyntax)
        {
            return statement;
        }

        return SyntaxFactory.Block(statement.WithoutLeadingTrivia()).WithLeadingTrivia(statement.GetLeadingTrivia());
    }

    public override SyntaxNode VisitIfStatement(IfStatementSyntax node)
    {
        var visited = (IfStatementSyntax)base.VisitIfStatement(node);

        return visited.WithStatement(Wrap(visited.Statement));
    }

    public override SyntaxNode VisitElseClause(ElseClauseSyntax node)
    {
        var visited = (ElseClauseSyntax)base.VisitElseClause(node);

        return visited.Statement is IfStatementSyntax ? visited : visited.WithStatement(Wrap(visited.Statement));
    }

    public override SyntaxNode VisitForStatement(ForStatementSyntax node)
    {
        var visited = (ForStatementSyntax)base.VisitForStatement(node);

        return visited.WithStatement(Wrap(visited.Statement));
    }

    public override SyntaxNode VisitForEachStatement(ForEachStatementSyntax node)
    {
        var visited = (ForEachStatementSyntax)base.VisitForEachStatement(node);

        return visited.WithStatement(Wrap(visited.Statement));
    }

    public override SyntaxNode VisitWhileStatement(WhileStatementSyntax node)
    {
        var visited = (WhileStatementSyntax)base.VisitWhileStatement(node);

        return visited.WithStatement(Wrap(visited.Statement));
    }

    public override SyntaxNode VisitDoStatement(DoStatementSyntax node)
    {
        var visited = (DoStatementSyntax)base.VisitDoStatement(node);

        return visited.WithStatement(Wrap(visited.Statement));
    }

    public override SyntaxNode VisitUsingStatement(UsingStatementSyntax node)
    {
        var visited = (UsingStatementSyntax)base.VisitUsingStatement(node);

        return visited.WithStatement(Wrap(visited.Statement));
    }

    public override SyntaxNode VisitLockStatement(LockStatementSyntax node)
    {
        var visited = (LockStatementSyntax)base.VisitLockStatement(node);

        return visited.WithStatement(Wrap(visited.Statement));
    }
}





