// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameEnum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace J2.Protocol {

  /// <summary>Holder for reflection information generated from GameEnum.proto</summary>
  public static partial class GameEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for GameEnum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5HYW1lRW51bS5wcm90bxIER2FtZSq0AgoIUGFja2V0SWQSCAoETk9ORRAA",
            "Eg8KC0NfRU5URVJHQU1FEGQSDwoLU19FTlRFUkdBTUUQZRIPCgtDX0xFQVZF",
            "R0FNRRBmEg8KC1NfTEVBVkVHQU1FEGcSDwoLQ19GSU5ETUFUQ0gQaBIPCgtT",
            "X0ZJTkRNQVRDSBBpEhEKDUNfQUNDRVBUTUFUQ0gQahIRCg1TX0FDQ0VQVE1B",
            "VENIEGsSCgoGQ19QSU5HEGwSCgoGU19QT05HEG0SCwoGQ19DSEFUEMgBEgsK",
            "BlNfQ0hBVBDJARIMCgdDX1NQQVdOEKwCEgwKB1NfU1BBV04QrQISCwoGQ19N",
            "T1ZFEK4CEgsKBlNfTU9WRRCvAhIUCg9DX1JFUVVFU1RSRVNVTFQQsAISFAoP",
            "U19SRVFVRVNUUkVTVUxUELECQg6qAgtKMi5Qcm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::J2.Protocol.PacketId), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Stable wire IDs. Never reuse retired IDs.
  /// </summary>
  public enum PacketId {
    [pbr::OriginalName("NONE")] None = 0,
    /// <summary>
    /// Basic 100~
    /// </summary>
    [pbr::OriginalName("C_ENTERGAME")] CEntergame = 100,
    [pbr::OriginalName("S_ENTERGAME")] SEntergame = 101,
    [pbr::OriginalName("C_LEAVEGAME")] CLeavegame = 102,
    [pbr::OriginalName("S_LEAVEGAME")] SLeavegame = 103,
    [pbr::OriginalName("C_FINDMATCH")] CFindmatch = 104,
    [pbr::OriginalName("S_FINDMATCH")] SFindmatch = 105,
    [pbr::OriginalName("C_ACCEPTMATCH")] CAcceptmatch = 106,
    [pbr::OriginalName("S_ACCEPTMATCH")] SAcceptmatch = 107,
    [pbr::OriginalName("C_PING")] CPing = 108,
    [pbr::OriginalName("S_PONG")] SPong = 109,
    /// <summary>
    /// Chat 200~
    /// </summary>
    [pbr::OriginalName("C_CHAT")] CChat = 200,
    [pbr::OriginalName("S_CHAT")] SChat = 201,
    /// <summary>
    /// InGame 300~
    /// </summary>
    [pbr::OriginalName("C_SPAWN")] CSpawn = 300,
    [pbr::OriginalName("S_SPAWN")] SSpawn = 301,
    [pbr::OriginalName("C_MOVE")] CMove = 302,
    [pbr::OriginalName("S_MOVE")] SMove = 303,
    [pbr::OriginalName("C_REQUESTRESULT")] CRequestresult = 304,
    [pbr::OriginalName("S_REQUESTRESULT")] SRequestresult = 305,
  }

  #endregion

}

#endregion Designer generated code
