var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;
var gt=AppDomain.CurrentDomain.GetAssemblies().SelectMany(a=>a.GetTypes()).Single(t=>t.FullName=="DigitalArena.DigitalArenaGame");
var g=UnityEngine.Object.FindAnyObjectByType(gt);
// This explicit Editor motor test initializes the arena independently of OAuth credentials.
gt.GetMethod("ResetRun",flags).Invoke(g,null);
gt.GetField("help",flags).SetValue(g,true);
var motor=(Component)gt.GetField("playableCharacter",flags).GetValue(g);
if(motor==null)throw new Exception("Avatar missing");
var mt=motor.GetType();var move=mt.GetMethod("MoveTo");var tick=mt.GetMethod("Tick");
if(!(bool)move.Invoke(motor,new object[]{new Vector3(6.6f,0,9.5f)}))throw new Exception("Legal bench target rejected");
var target=(Vector3)mt.GetProperty("Destination").GetValue(motor);
foreach(var p in new[]{new Vector3(6.71f,0,0),new Vector3(0,0,9.61f),new Vector3(-6.71f,0,0),new Vector3(0,0,-9.61f)})
 if((bool)move.Invoke(motor,new object[]{p}) || (Vector3)mt.GetProperty("Destination").GetValue(motor)!=target)throw new Exception("Outside target changed destination");
tick.Invoke(motor,new object[]{10f,true});
if(Vector3.Distance(motor.transform.position,target)>.01f || (bool)mt.GetProperty("IsMoving").GetValue(motor))throw new Exception("Arrival failed");
var animation=motor.GetComponent<Animation>();
foreach(var n in new[]{"Idle","Walk","Attack","Death"}) if(animation.GetClip(n)==null)throw new Exception("Missing clip "+n);
if(motor.GetComponentsInChildren<SkinnedMeshRenderer>().Any(r=>r.sharedMesh==null || r.bones.Any(b=>b==null) || r.gameObject.layer!=30))throw new Exception("Renderer not connected");
gt.GetField("help",flags).SetValue(g,false);
gt.GetField("shopOpen",flags).SetValue(g,false);gt.GetField("shopProgress",flags).SetValue(g,0f);
var pointer=gt.GetMethod("HandlePointer",flags);
var current=(Vector3)mt.GetProperty("Destination").GetValue(motor);
pointer.Invoke(g,new object[]{EventType.MouseDown,0,1,new Vector2(1300,225)});
if((Vector3)mt.GetProperty("Destination").GetValue(motor)!=current)throw new Exception("UI moved avatar");
gt.GetMethod("ViewPlayer",flags).Invoke(g,new object[]{true});
if(!(bool)gt.GetField("viewingOpponent",flags).GetValue(g))throw new Exception("Opponent view failed");
gt.GetMethod("ViewPlayer",flags).Invoke(g,new object[]{false});
mt.GetMethod("ResetPosition").Invoke(motor,new object[]{new Vector3(0,.25f,-7.9f)});
gt.GetField("help",flags).SetValue(g,true);
return "PASS: avatar, 4 clips, renderer/layer, own-to-opponent bench target, four outside edges rejected without clamping, arrival, UI isolation, list view selection";
